// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwfuygmhcfmbzkewiuuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3ZnV5Z21oY2ZtYnprZXdpdXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTQ3ODksImV4cCI6MjA2Njk3MDc4OX0.pe1U9ZqkH48mJpnAuFAPazpmv7aDX2MA_M4BheFyUGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});